services:
  config-service:
    build: config-service
    ports:
      - 8081:8081
    restart: always
  eureka:
    build: eureka
    ports:
      - 8761:8761
    restart: always
    depends_on:
      config-service:
          condition: service_healthy