spring:
  application:
    name: eureka
server:
  port: 8761

eureka:
  instance:
    hostname: http://192.168.100.16
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://192.168.100.16:${server.port}/eureka


