spring:
  application:
    name: eureka
server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.100.16
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://eureka:${server.port}/eureka


