server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10 # Retry interval
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: mc_recaudacion
        uri: http://192.168.100.16:8002
        predicates:
        - Path=/cajas/**
