server:
  port: 8082

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://eureka:8761/eureka/  # Usa el nombre del servicio Eureka (recomendado)

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Habilita el discovery locator
      routes:
        - id: mc_recaudacion
          uri: http://mc_recaudacion:8002 # Usa el nombre del servicio mc_recaudacion con lb://
          predicates:
            - Path=/cajas/**