server:
  port: 9090
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: 127.0.0.1
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mc_recaudacion
          uri: lb://mc_recaudacion
          predicates: 
            - Path=/cajas/**

