spring:
  application:
    name: mc_recaudacion
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # Use the IP address to avoid DNS issues
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
server:
  port: 8001 # Ensure this is the correct port for your service
management:
  endpoints:
    web:
      exposure:
        include: health,info
