server:
  port: 8002

spring:
  application:
    name: mc_recaudacion  # Nombre de tu microservicio

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${spring.application.name}