server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: comercializacion
          uri: https://github.com/ortizln/erp_epmapat
          search-paths: config-data
  application:
    name: erp_epmapat